### ISSUE TITLE
Update link for VFGEN documentation

### ISSUE THREAD

**Issue by WarrenWeckesser** [a-kramer/SBtabVFGEN#1]
This looks like a cool project!  I hope you find VFGEN useful.  After a long hiatus, I'm working on VFGEN again, and I hope to make a new release this summer.

Could you update the VFGEN documentation link in README.md to point to https://warrenweckesser.github.io/vfgen/?  Last year, I let my registration of `www.<my.name>.net` expire (I don't even want to type the actual name, on the off chance that someone will click on it), and when I went to reacquire the name a few months ago, I found I'd been cybersquatted, and the name now redirects to advertisements.  Until I find the energy to hire a lawyer to get the name back, I'm using github pages for the documentation.

**Comment by WarrenWeckesser** [comment]
Here's a pull request for the updated link: https://github.com/a-kramer/SBtabVFGEN/pull/2

**Comment by a-kramer** [comment]
Hello,
 I'm so sorry for the delayed response. I have a deadline coming up and a
lot of other things got delayed as well. But, now I think that I fixed it.
It's so great to hear that you are resuming that work.
All the Best,
Andrei

**Comment by WarrenWeckesser** [comment]
Thanks!
